using System.Collections.Generic;
using Newtonsoft.Json;

namespace OmniKassa.Model.Response
{
    /// <summary>
    /// Order details, including the latest status.
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public class OrderStatusResult
    {
        /// <summary>
        /// Unique order identifier, generated by Rabo Smart Pay when an order is announced.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Merchant order id, as provided during order announcement.
        /// </summary>
        [JsonProperty(PropertyName = "merchantOrderId")]
        public string MerchantOrderId { get; set; }

        /// <summary>
        /// The status of the order
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// This field contains the original order amount as supplied in the order announcement call.
        /// </summary>
        [JsonProperty(PropertyName = "totalAmount")]
        public Money TotalAmount { get; set; }

        /// <summary>
        /// List of transactions.
        /// </summary>
        [JsonProperty(PropertyName = "transactions")]
        public List<TransactionInfo> Transactions { get; set; }

        /// <summary>
        /// Requested fast checkout details
        /// </summary>
        [JsonProperty(PropertyName = "checkoutDetails")]
        public CheckoutDetailsResponse CheckoutDetails { get; set; }

        /// <summary>
        /// Initializes an empty OrderStatusResult
        /// </summary>
        public OrderStatusResult()
        {
            Transactions = new List<TransactionInfo>();
        }
    }
}
